"""Finite-horizon Stackelberg control primitives.

The leader (insurer) chooses a cap first.  The follower (policyholder) then
observes the state and that cap and chooses ``CONTINUE`` or
``FULL_WITHDRAWAL`` using *only* the policyholder value function.  The leader
anticipates this best response and maximises its own, separate value function.

This small tabular solver is the exact reference implementation used to test
the ordering and tie-breaking of the fitted-Q approximation in
``portfolio_simulations.optimize_crediting_rate_lsmc``.  It is intentionally
free of product cashflow logic: production rewards are always generated by
the monthly projector and only then supplied to an approximate solver.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Optional, Sequence

import numpy as np
from numpy.typing import NDArray


Array = NDArray[np.float64]
IntArray = NDArray[np.int64]


class PolicyholderAction(IntEnum):
    """Admissible follower actions in the generic product."""

    CONTINUE = 0
    FULL_WITHDRAWAL = 1


@dataclass(frozen=True)
class TabularStackelbergProblem:
    """One finite-state, finite-horizon bilevel control problem.

    Reward arrays have shape ``(time, state, leader_action, follower_action)``.
    ``next_state`` has the same shape and contains either a valid state index
    for the next time or ``-1`` for a terminal transition.  The two reward
    tensors deliberately remain separate; no weighted or blended objective is
    accepted by this API.
    """

    policyholder_reward: Array
    insurer_reward: Array
    next_state: IntArray
    action_values: Array
    initial_state: int = 0
    policyholder_tie_tolerance: float = 1.0e-12
    insurer_tie_tolerance: float = 1.0e-12

    def __post_init__(self) -> None:
        ph = np.asarray(self.policyholder_reward, dtype=float)
        insurer = np.asarray(self.insurer_reward, dtype=float)
        transitions = np.asarray(self.next_state, dtype=np.int64)
        actions = np.asarray(self.action_values, dtype=float)
        expected_rank = 4
        if ph.ndim != expected_rank or ph.shape[-1] != len(PolicyholderAction):
            raise ValueError(
                "Rewards must have shape (time, state, leader action, 2)."
            )
        if insurer.shape != ph.shape or transitions.shape != ph.shape:
            raise ValueError("Reward and transition arrays must have equal shapes.")
        if actions.ndim != 1 or actions.size != ph.shape[2]:
            raise ValueError("action_values must align with the leader-action axis.")
        if not np.all(np.isfinite(ph)) or not np.all(np.isfinite(insurer)):
            raise ValueError("Stackelberg rewards must be finite.")
        if not np.all(np.isfinite(actions)) or np.any(actions < 0.0):
            raise ValueError("Leader action values must be finite and non-negative.")
        if np.any(np.diff(actions) <= 0.0):
            raise ValueError("Leader action values must be strictly increasing.")
        n_states = ph.shape[1]
        if np.any((transitions < -1) | (transitions >= n_states)):
            raise ValueError("next_state contains an invalid state index.")
        if not 0 <= int(self.initial_state) < n_states:
            raise ValueError("initial_state is outside the state space.")
        for value in (
            self.policyholder_tie_tolerance,
            self.insurer_tie_tolerance,
        ):
            if not np.isfinite(value) or value < 0.0:
                raise ValueError("Tie tolerances must be finite and non-negative.")
        # Defensive immutable snapshots keep enumeration tests reproducible.
        for name, value in (
            ("policyholder_reward", ph),
            ("insurer_reward", insurer),
            ("next_state", transitions),
            ("action_values", actions),
        ):
            snapshot = np.array(value, copy=True)
            snapshot.flags.writeable = False
            object.__setattr__(self, name, snapshot)

    @property
    def horizon(self) -> int:
        return int(self.policyholder_reward.shape[0])

    @property
    def n_states(self) -> int:
        return int(self.policyholder_reward.shape[1])

    @property
    def n_leader_actions(self) -> int:
        return int(self.policyholder_reward.shape[2])


@dataclass(frozen=True)
class TabularStackelbergSolution:
    """Exact subgame-perfect Stackelberg solution."""

    policyholder_value: Array
    insurer_value: Array
    leader_action_index: IntArray
    policyholder_action_index: IntArray
    policyholder_q: Array
    insurer_q_after_best_response: Array
    admissible_leader_action_indices: tuple[int, ...]

    @property
    def first_leader_action_index(self) -> int:
        return int(self.leader_action_index[0, 0])


def _continuation_value(
    next_values: Array,
    transition: int,
) -> float:
    return 0.0 if transition < 0 else float(next_values[transition])


def solve_tabular_stackelberg(
    problem: TabularStackelbergProblem,
    *,
    admissible_leader_action_indices: Optional[Sequence[int]] = None,
) -> TabularStackelbergSolution:
    """Solve the repeated leader/follower problem by backward induction.

    Ties in the follower problem resolve to ``CONTINUE``.  This is the
    conservative product fallback and prevents regression noise from creating
    artificial surrender.  Leader ties resolve to the lowest admissible cap,
    giving deterministic results without manufacturing flexibility value.

    Passing a singleton ``admissible_leader_action_indices`` solves a fixed-cap
    policy as a strict subclass of the same control problem.
    """

    if admissible_leader_action_indices is None:
        admissible = tuple(range(problem.n_leader_actions))
    else:
        admissible = tuple(int(index) for index in admissible_leader_action_indices)
        if not admissible:
            raise ValueError("At least one leader action must be admissible.")
        if len(set(admissible)) != len(admissible):
            raise ValueError("Admissible leader actions must be unique.")
        if any(index < 0 or index >= problem.n_leader_actions for index in admissible):
            raise ValueError("An admissible leader action index is out of range.")
        admissible = tuple(sorted(admissible))

    horizon = problem.horizon
    n_states = problem.n_states
    n_actions = problem.n_leader_actions
    ph_value = np.zeros((horizon + 1, n_states), dtype=float)
    insurer_value = np.zeros((horizon + 1, n_states), dtype=float)
    leader_policy = np.full((horizon, n_states), -1, dtype=np.int64)
    follower_policy = np.full((horizon, n_states, n_actions), -1, dtype=np.int64)
    ph_q = np.full(
        (horizon, n_states, n_actions, len(PolicyholderAction)),
        np.nan,
        dtype=float,
    )
    insurer_q = np.full((horizon, n_states, n_actions), np.nan, dtype=float)

    for time in range(horizon - 1, -1, -1):
        for state in range(n_states):
            for leader_action in admissible:
                for follower_action in PolicyholderAction:
                    transition = int(problem.next_state[
                        time, state, leader_action, int(follower_action)
                    ])
                    ph_q[time, state, leader_action, int(follower_action)] = (
                        problem.policyholder_reward[
                            time, state, leader_action, int(follower_action)
                        ]
                        + _continuation_value(ph_value[time + 1], transition)
                    )

                continue_value = ph_q[
                    time, state, leader_action, PolicyholderAction.CONTINUE
                ]
                withdrawal_value = ph_q[
                    time, state, leader_action,
                    PolicyholderAction.FULL_WITHDRAWAL,
                ]
                follower_action = (
                    PolicyholderAction.FULL_WITHDRAWAL
                    if withdrawal_value
                    > continue_value + problem.policyholder_tie_tolerance
                    else PolicyholderAction.CONTINUE
                )
                follower_policy[time, state, leader_action] = int(follower_action)
                transition = int(problem.next_state[
                    time, state, leader_action, int(follower_action)
                ])
                insurer_q[time, state, leader_action] = (
                    problem.insurer_reward[
                        time, state, leader_action, int(follower_action)
                    ]
                    + _continuation_value(insurer_value[time + 1], transition)
                )

            best = admissible[0]
            best_value = insurer_q[time, state, best]
            for candidate in admissible[1:]:
                candidate_value = insurer_q[time, state, candidate]
                if candidate_value > best_value + problem.insurer_tie_tolerance:
                    best = candidate
                    best_value = candidate_value
                elif (
                    abs(candidate_value - best_value)
                    <= problem.insurer_tie_tolerance
                    and problem.action_values[candidate]
                    < problem.action_values[best]
                ):
                    best = candidate
                    best_value = candidate_value
            leader_policy[time, state] = best
            response = int(follower_policy[time, state, best])
            ph_value[time, state] = ph_q[time, state, best, response]
            insurer_value[time, state] = insurer_q[time, state, best]

    return TabularStackelbergSolution(
        policyholder_value=ph_value[:-1],
        insurer_value=insurer_value[:-1],
        leader_action_index=leader_policy,
        policyholder_action_index=follower_policy,
        policyholder_q=ph_q,
        insurer_q_after_best_response=insurer_q,
        admissible_leader_action_indices=admissible,
    )


__all__ = [
    "PolicyholderAction",
    "TabularStackelbergProblem",
    "TabularStackelbergSolution",
    "solve_tabular_stackelberg",
]
